// scripts/gen-theme.mjs
// Generates src/theme/tokens.css from src/theme/tokens.json (vendored copy of
// megaforge/design/tokens.json). DO NOT edit tokens.css by hand — edit the JSON
// and re-run `npm run gen:theme`.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const SRC = join(root, "src/theme/tokens.json");
const OUT = join(root, "src/theme/tokens.css");

const t = JSON.parse(readFileSync(SRC, "utf8"));
const v = [];
const push = (name, val) => v.push(`  --${name}: ${val};`);

// surfaces
const baseMap = { void: "surface-void", surface: "surface", raised: "surface-raised", overlay: "surface-overlay", border: "border", borderStrong: "border-strong" };
for (const [k, name] of Object.entries(baseMap)) push(name, t.color.base[k]);
// text ramp
for (const k of ["hi", "base", "lo", "faint"]) push(`text-${k}`, t.color.text[k]);
// accents (seraph also exposed as the bare --accent)
for (const [name, a] of Object.entries(t.color.accent)) {
  if (name === "seraph") push("accent", a.value);
  push(`accent-${name}`, a.value);
}
// semantic
for (const [k, val] of Object.entries(t.color.semantic)) push(k, val);
// channel data colors
if (t.color.channel) for (const [k, val] of Object.entries(t.color.channel)) push(`channel-${k}`, val);
// fonts
push("font-ui", t.type.font.ui);
push("font-mono", t.type.font.mono);
// type.weight intentionally omitted — weights are used as literal numbers in CSS.
// type scale
for (const [k, s] of Object.entries(t.type.scale)) { push(`fs-${k}`, s.size); push(`lh-${k}`, s.line); }
// space + radius
for (const [k, val] of Object.entries(t.space)) push(`space-${k}`, val);
for (const [k, val] of Object.entries(t.radius)) push(`radius-${k}`, val);

const ALIASES = `
  /* --- app-semantic aliases (existing var names -> Empyrean tokens) --- */
  --bg-app: var(--surface-void);
  --bg-panel: var(--surface);
  --bg-surface: var(--surface-raised);
  --bg-input: var(--surface-void);
  --border-focus: var(--accent);
  --text-primary: var(--text-hi);
  --text-secondary: var(--text-lo);
  --text-disabled: var(--text-faint);
  --accent-active: var(--accent);
  --accent-fm: var(--channel-fm);
  --accent-psg: var(--channel-psg);
  --accent-dac: var(--channel-dac);
  --knob-track: var(--surface-overlay);
  --knob-fill: var(--accent);
  --envelope-line: var(--accent);
  --envelope-fill: rgba(251, 191, 36, 0.15);
  --carrier-highlight: #FFCC44;`;

const css = `/* GENERATED by scripts/gen-theme.mjs from src/theme/tokens.json -- DO NOT EDIT BY HAND. */
:root {
${v.join("\n")}
${ALIASES}
}
`;

// self-check: required vars must be present (before we write anything)
const required = [
  "--surface-void", "--surface", "--surface-raised", "--surface-overlay",
  "--accent", "--text-hi", "--text-lo", "--text-faint",
  "--success", "--channel-fm", "--channel-psg", "--channel-dac",
  "--bg-app", "--accent-fm",
];
const missing = required.filter((r) => !css.includes(`${r}:`));
if (missing.length) { console.error("gen-theme: MISSING vars:", missing); process.exit(1); }

writeFileSync(OUT, css);
console.log(`gen-theme: wrote src/theme/tokens.css (${v.length} tokens + aliases)`);
