// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async playFmTestTone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_fm_test_tone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playPsgTestTone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_psg_test_tone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopAllSound() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_all_sound") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createProject(path: string, name: string, driverId: string, tempo: number, timeSigNum: number, timeSigDen: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { path, name, driverId, tempo, timeSigNum, timeSigDen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openProject(path: string) : Promise<Result<Song, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_project", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeProject() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjectInfo() : Promise<Result<SongMetadata | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit the song-level tempo / time signature after creation. Returns the
 * updated metadata; marks the project dirty (persisted on next save).
 * NOT undoable in v1 — metadata sits outside the track undo snapshot.
 */
async updateProjectMetadata(tempo: number, timeSigNum: number, timeSigDen: number) : Promise<Result<SongMetadata, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project_metadata", { tempo, timeSigNum, timeSigDen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDrivers() : Promise<Result<DriverInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_drivers") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDriverInfo(driverId: string) : Promise<Result<DriverDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_driver_info", { driverId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addFmInstrument(instrument: FmInstrument) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_fm_instrument", { instrument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFmInstrument(id: string, instrument: FmInstrument) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_fm_instrument", { id, instrument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFmInstrument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_fm_instrument", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listFmInstruments() : Promise<Result<FmInstrument[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_fm_instruments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewFmInstrument(id: string, midiNote: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_fm_instrument", { id, midiNote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopFmPreview() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_fm_preview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPsgInstrument(instrument: PsgInstrument) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_psg_instrument", { instrument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePsgInstrument(id: string, instrument: PsgInstrument) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_psg_instrument", { id, instrument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePsgInstrument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_psg_instrument", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPsgInstruments() : Promise<Result<PsgInstrument[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_psg_instruments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewPsgInstrument(id: string, midiNote: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_psg_instrument", { id, midiNote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDacWav(wavPath: string, targetRate: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_dac_wav", { wavPath, targetRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDacRaw(pcmPath: string, sampleRate: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_dac_raw", { pcmPath, sampleRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDacInstrument(id: string, instrument: DacInstrument) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dac_instrument", { id, instrument }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconvertDac(id: string, newRate: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconvert_dac", { id, newRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDacInstrument(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dac_instrument", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDacInstruments() : Promise<Result<DacInstrument[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dac_instruments") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewDac(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_dac", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDacPcmData(id: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dac_pcm_data", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addTrack(name: string, channel: ChannelAssignment, instrumentId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_track", { name, channel, instrumentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTrack(id: string, name: string, channel: ChannelAssignment, instrumentId: string | null, muted: boolean, solo: boolean, volume: number, pan: Pan, pitchOffset: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_track", { id, name, channel, instrumentId, muted, solo, volume, pan, pitchOffset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTrack(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_track", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTracks() : Promise<Result<Track[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tracks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One track's instrument binding, as a bare id — nothing else crosses.
 * 
 * The piano roll's audition path needs exactly this and nothing more, and it
 * runs on the interactive path: every note press, every grid double-click,
 * every keys-column click, and once per new pitch of a Draw-Mode paint drag.
 * Reaching it through `list_tracks` serialized the whole track/region/note
 * tree — the entire song — to read one field, per keystroke (F26).
 * 
 * Deliberately a fresh read rather than a frontend cache: the binding changes
 * from surfaces the piano roll never hears about (a library drop on the track
 * header, an unbind, a track delete), so anything cached here would audition
 * the previous voice until something unrelated happened to refetch.
 * 
 * An unknown track id is `Ok(None)`, not an error: the caller's question is
 * "what should this audition play", and "nothing" is a valid answer for a
 * track that was deleted out from under an open roll.
 */
async getTrackInstrument(trackId: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_instrument", { trackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addRegion(trackId: string, startTick: number, durationTicks: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_region", { trackId, startTick, durationTicks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRegion(trackId: string, regionId: string, startTick: number, durationTicks: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_region", { trackId, regionId, startTick, durationTicks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveRegion(srcTrackId: string, regionId: string, dstTrackId: string, startTick: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_region", { srcTrackId, regionId, dstTrackId, startTick }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateRegion(trackId: string, regionId: string, atStartTick: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_region", { trackId, regionId, atStartTick }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRegion(trackId: string, regionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_region", { trackId, regionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addNote(trackId: string, regionId: string, tick: number, pitch: number, velocity: number, durationTicks: number, instrumentId: string | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_note", { trackId, regionId, tick, pitch, velocity, durationTicks, instrumentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateNote(trackId: string, regionId: string, noteIndex: number, tick: number, pitch: number, velocity: number, durationTicks: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_note", { trackId, regionId, noteIndex, tick, pitch, velocity, durationTicks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(trackId: string, regionId: string, noteIndex: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { trackId, regionId, noteIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set (or clear, with `None`) the per-note voice on a batch of selected
 * notes — one undoable edit. Validated in the manager: kind gate (FM voice
 * ↔ FM channel, …) then the "voice-overlap" gate (an edit may not leave
 * notes with DIFFERENT effective voices overlapping on one channel).
 */
async setNoteInstrument(trackId: string, regionId: string, noteIndices: number[], instrumentId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_note_instrument", { trackId, regionId, noteIndices, instrumentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Undo the last song edit and return the restored tracks (the frontend
 * re-renders from this — same payload shape as `list_tracks`). A no-op
 * (empty stack) returns the current tracks unchanged.
 */
async undo() : Promise<Result<Track[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async redo() : Promise<Result<Track[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a coalescing undo group (drag gesture / batch loop): until
 * `end_undo_group`, only the first mutation pushes an undo snapshot.
 */
async beginUndoGroup() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_undo_group") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endUndoGroup() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_undo_group") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUndoState() : Promise<Result<UndoState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_undo_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transportPlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transport_play") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transportStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transport_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transportSeek(tick: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transport_seek", { tick }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transportSetLoop(startTick: number, endTick: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transport_set_loop", { startTick, endTick }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transportClearLoop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transport_clear_loop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlaybackState() : Promise<Result<PlaybackState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_playback_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reloadSequence() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_sequence") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMasterVolume(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_master_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getChannelOverlaps() : Promise<Result<OverlapWarning[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_channel_overlaps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSong(outputDir: string) : Promise<Result<ExportResult, ExportFailure>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_song", { outputDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportWav(outputPath: string, durationSeconds: number | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_wav", { outputPath, durationSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSong(sourcePath: string, parentDir: string, dacDir: string | null) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_song", { sourcePath, parentDir, dacDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importZyrinxSong(romPath: string, parentDir: string, gameId: number) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_zyrinx_song", { romPath, parentDir, gameId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFmFile(filePath: string) : Promise<Result<FmFileImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_fm_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportVgm(outputPath: string, durationSeconds: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_vgm", { outputPath, durationSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importVgm(vgmPath: string, parentDir: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_vgm", { vgmPath, parentDir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryList(filter: LibraryFilter) : Promise<Result<LibraryListEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_list", { filter }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryGames() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_games") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryGetEntry(hash: string) : Promise<Result<LibraryEntryDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_get_entry", { hash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryRescan() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_rescan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan/parse warnings from the last rescan (corrupt overrides/roots files,
 * unreadable entries). The UI surfaces these so quarantine events are visible.
 */
async libraryWarnings() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_warnings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryAudition(hash: string, midiNote: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_audition", { hash, midiNote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a library audition (FM or PSG) without resetting the whole mix.
 * 
 * - Forces release rate $F on ch0's four operators before keying off:
 * imported patches (GYB/TFI) can carry RR=0 and would ring indefinitely on
 * `FmKeyOff` alone. `do_preview_fm` reprograms the full patch on the next
 * audition anyway, so clobbering SL/RR here is safe.
 * - Sends `StopPreview`, which clears a looping PSG envelope preview (and
 * any DAC preview) and invalidates the sequencer's ch0 FM patch cache so
 * playback recovers on ch0's next note-on.
 * 
 * `stop_all_sound` (`AudioCommand::Panic`) stays reserved for the global
 * panic button — it resets both chips but leaves the sequencer's patch cache
 * intact, which kills FM output until the next stop/seek.
 */
async libraryStopAudition() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_stop_audition") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryAddToProject(hash: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_add_to_project", { hash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drag-to-track swap: bind a library voice to a track, reusing a project
 * instrument with the same content hash or adding the voice first. Returns
 * the bound project instrument id. Kind-checked (FM voice ↔ FM track, PSG
 * voice ↔ PSG/noise track) in the manager.
 */
async libraryAssignToTrack(trackId: string, hash: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_assign_to_track", { trackId, hash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve a library entry into the project's instrument bank WITHOUT
 * touching any track: reuse a same-content-hash project instrument or add
 * the voice. Returns the project instrument id. Backs the piano-roll
 * note-voice drop, where `set_note_instrument` needs a project instrument
 * id but the drag payload carries a library hash.
 */
async libraryEnsureProjectInstrument(hash: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_ensure_project_instrument", { hash }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async librarySaveFromProject(kind: string, id: string, name: string | null, tags: string[]) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_save_from_project", { kind, id, name, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryImportFiles(paths: string[]) : Promise<Result<LibraryImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_import_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async librarySetTags(hash: string, tags: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_set_tags", { hash, tags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async librarySetFavorite(hash: string, favorite: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_set_favorite", { hash, favorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryRootsGet() : Promise<Result<RootInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_roots_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryRootAdd(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_root_add", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async libraryRootRemove(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_root_remove", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ChannelAssignment = { Fm: number } | { Psg: number } | "PsgNoise" | { Dac: number }
export type ChannelLayout = { fmChannels: FmChannelInfo[]; psgChannels: PsgChannelInfo[]; dacChannels: DacChannelInfo[] }
export type DacChannelInfo = { index: number; name: string }
export type DacInstrument = { id: string; name: string; targetSampleRate: number; loopStart: number | null; loopLength: number | null; originalFile: string; pcmFile: string; sourceIsRaw: boolean; metadata: InstrumentMetadata }
export type DriverDetail = { id: string; name: string; layout: ChannelLayout; features: DriverFeature[] }
export type DriverFeature = "SsgEg" | "Fm3SpecialMode" | "MultiDac" | "Dpcm" | "PseudoStereo"
export type DriverInfo = { id: string; name: string }
export type ExportError = { trackName: string; regionIndex: number | null; noteIndex: number | null; message: string }
export type ExportFailure = { errors: ExportError[] }
export type ExportResult = { files: string[] }
export type FmChannelInfo = { index: number; name: string; supportsSpecialMode: boolean }
export type FmFileImportResponse = { format: string; count: number; ids: string[] }
export type FmInstrument = { id: string; name: string; algorithm: number; feedback: number; operators: [FmOperator, FmOperator, FmOperator, FmOperator]; metadata: InstrumentMetadata }
export type FmOperator = { detune: number; multiple: number; rateScale: number; attackRate: number; ampMod: boolean; d1r: number; d2r: number; sustainLevel: number; releaseRate: number; totalLevel: number; ssgEg?: number }
export type ImportResult = { projectDir: string; metadata: SongMetadata; trackCount: number; instrumentCount: number; warnings: ImportWarning[] }
export type ImportWarning = { channel: string; message: string }
export type InstrumentBank = { fm: FmInstrument[]; psg: PsgInstrument[]; dac: DacInstrument[] }
export type InstrumentMetadata = { category: string; author: string; tags: string[] }
/**
 * Full instrument payload for the selected entry's detail card. A separate
 * command (rather than fields on `LibraryListEntry`) keeps `library_list`
 * lean — the list carries hundreds of entries, the card needs exactly one.
 */
export type LibraryEntryDetail = { name: string; game: string; tags: string[]; instrument: LibraryInstrument }
export type LibraryFilter = { text?: string | null; kind?: string | null; game?: string | null; tag?: string | null; favoritesOnly?: boolean }
export type LibraryImportResult = { written: number; errors: string[] }
/**
 * `{"type":"fm","instrument":{...}}` shape per the spec.
 */
export type LibraryInstrument = { type: "fm"; instrument: FmInstrument } | { type: "psg"; instrument: PsgInstrument }
export type LibraryListEntry = { hash: string; name: string; 
/**
 * "fm" | "psg"
 */
kind: string; game: string; tags: string[]; favorite: boolean; rootLabel: string }
export type NoiseMode = { Periodic: number } | { White: number }
export type Note = { tick: number; pitch: number; velocity: number; durationTicks: number; instrumentId?: string | null; detune?: number; panOverride?: number | null; modulation?: NoteModulation | null }
export type NoteModulation = { wait: number; speed: number; delta: number; steps: number }
export type OverlapWarning = { channelName: string; tickStart: number; tickEnd: number; trackIds: string[] }
export type Pan = "Left" | "Right" | "Center"
export type PlaybackState = { playing: boolean; tick: number; loopStart: number | null; loopEnd: number | null; channelLevels: number[] }
export type PsgChannelInfo = { index: number; name: string; isNoise: boolean }
export type PsgInstrument = { id: string; name: string; volumeSequence: number[]; loopPoint: number | null; silenceOnEnd?: boolean; noiseMode: NoiseMode | null; smpsEnvelopeIndex?: number | null; metadata: InstrumentMetadata }
export type Region = { id: string; startTick: number; durationTicks: number; notes: Note[]; instrumentId?: string | null }
export type RootInfo = { label: string; path: string; 
/**
 * "bundled" | "user" | "custom"
 */
kind: string }
/**
 * Full in-memory song representation including instruments.
 */
export type Song = { metadata: SongMetadata; tracks: Track[]; instruments: InstrumentBank }
export type SongMetadata = { name: string; tempo: number; timeSignature: [number, number]; ticksPerBeat: number; driverId: string }
export type Track = { id: string; name: string; channel: ChannelAssignment; instrumentId: string | null; regions: Region[]; muted: boolean; solo: boolean; volume: number; pan: Pan; pitchOffset?: number; modulation?: TrackModulation | null }
export type TrackModulation = { wait: number; speed: number; delta: number; steps: number }
/**
 * Combined undo/redo/dirty state for the frontend (Save indicator,
 * menu enablement, close-confirm).
 */
export type UndoState = { canUndo: boolean; canRedo: boolean; dirty: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
